name: Build and Test Utils

on:
  push:
    paths:
      - 'packages/utils/**'
  pull_request:
    paths:
      - 'packages/utils/**'

jobs:
  build-utils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build CentOS 5 i386 Builder
        working-directory: packages/utils/centos-5-i386-build
        run: |
          # Create output directory
          mkdir -p output
          
          # Build the Docker image with detailed output
          echo "Building Docker image..."
          docker build --progress=plain -t centos5-i386-builder . || {
            echo "Docker build failed"
            exit 1
          }
          
          # Run the container with error handling
          echo "Running container..."
          docker run --rm -v $(pwd)/output:/output centos5-i386-builder /root/prepare.sh || {
            echo "Container execution failed"
            exit 1
          }
          
          # Verify the output file exists
          if [ ! -f "output/centos-5-i386.tar.gz" ]; then
            echo "Error: Build artifact not found"
            exit 1
          fi
          
          # Move the file to the correct location
          mv output/centos-5-i386.tar.gz .
          rm -rf output
          
          echo "Build completed successfully!" 